In [2]:
import numpy as np

In [4]:
#numpy 저장/불러오기
#1.단일 객체 저장 : np.save()
array = np.arange(0,10)
np.save('saved.npy',array)
#2.단일 객체 불러오기 : np.load
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#복수 객체 저장 : np.savez()
array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz',arr1=array1, arr2=array2)

In [6]:
#복수 객체 불러오기 : np.load
data = np.load('saved.npz')
result1 = data['arr1']
result2 = data['arr2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [7]:
#numpy 원소 오름차순 정렬
array = np.array([5,9,10,3,1])
print(array)
array.sort()
print(array)


[ 5  9 10  3  1]
[ 1  3  5  9 10]


In [8]:
#내림차순
print(array[::-1])

[10  9  5  3  1]


In [12]:
#각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis = 0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [13]:
#균일한 간격으로 데이터 생성
#np.linspace(start_vlaue, end_value, 개수)
array = np.linspace(0,10,5) 
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
#난수(random 값)의 재연
#실행마다 결과 달라짐)
print(np.random.randint(0,10,(2,3)))

[[0 3 0]
 [4 4 3]]


In [19]:
#실행마다 결과 동일
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

[[4 9 6]
 [3 3 7]]


In [21]:
#numpy 배열 객체 복사 - 메모리를 공유 
array1 = np.arange(0,10)
print(array1)
array2 = array1
array2[0]=99
print(array1)

[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


In [22]:
#numpy 배열 객체 복사 
array1 = np.arange(0,10)
print(array1)
array2 = array1.copy()
array2[0]=99
print(array1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
#중복된 원소 제거 : np.unique()
array = np.array([1,1,2,2,2,3,3,4])
print(np.unique(array))

[1 2 3 4]
