In [1]:
import numpy as np
array = np.random.randint(1,10,size = 4).reshape(2,2)
print(array)

[[7 8]
 [2 9]]


In [5]:
a = np.array([[1,2],[3,4]])
print(a.shape)
print(a.size)

(2, 2)
4


In [7]:
#배열에 상수 곱하기 
result_array = array*10
print(result_array)

[[70 80]
 [20 90]]


In [8]:
#서로 다른 형태의 numpy 연산 : Broadcasting
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)

array3 = array1+array2
print(array3)

[[0 2]
 [2 4]]


In [12]:
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2], axis=0)
array4 = np.arange(0,4).reshape(4,1)


print(array3)
print(array4)
print(array3+4)
print(array3+array4)


[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [14]:
#마스킹연산 : 각 원소에 대하여 체크 함
array1 = np.arange(16).reshape(4,4)
print(array1)
array2 = array1<10
print(array2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [16]:
#array 2가 True인 값만 100을 대입  ~ 색상이 너무 밝을 때 값을 바꿔주는 등..
#조건문을 활용해 작업하는 것보다 마스킹 연산이 훨씬 빠름

array1[array2] = 100   
print(array1)

[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [21]:
#집계함수
array = np.arange(16).reshape(4,4)
print("최댓값 : ",np.max(array))
print("최솟값 : ",np.min(array))
print("합계 : ",np.sum(array))
print("평균값 : ", np.mean(array))

최댓값 :  15
최솟값 :  0
합계 :  120
평균값 :  7.5


In [23]:
print(array)
print("합계: ",np.sum(array, axis=0))  #행을 기준으로 더한다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]
