In [32]:
#배열과 관련된 거의 모든 작업을 수행할 수 있음. 
import numpy as np


In [47]:
list_data = [1,2,3]
print(list_data)
print(type(list_data))

[1, 2, 3]
<class 'list'>


In [48]:
list_data = [1,2,3]
array = np.array(list_data)  #특정 리스트 데이터(list_data) 를 numpy 자료형으로 변형   
print(array)

[1 2 3]


In [50]:
print(array.dtype)
print(array.size)
print(type(array))
print(array.shape)

int32
3
<class 'numpy.ndarray'>
(3,)


In [52]:
a = np.array([[1],[1],[1]])
print(a)
print(a.shape)

[[1]
 [1]
 [1]]
(3, 1)


In [36]:
#numpy는 리스트와 마찬가지로 특정 index에 접근이 가능하다
print(array[2])

3


In [37]:
 #0부터 3까지 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [38]:
array2 = np.zeros((3,3), dtype = float)  #dtype 으로 숫자의 type을 지정해준다 
print(array2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
array3 = np.ones((3,3), dtype = 'str')
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [53]:
#0부터 9까지 랜덤으로 초기화 된 배열 만들기
array4 = np.random.randint(0,9,(3,3))  #0~8 중에 랜덤한 수로 3by3 행렬 만들기
print(array4)

[[7 7 0]
 [1 8 4]
 [6 2 1]]


In [55]:
#np.zeros()
a= np.zeros((2,2))
print(a.shape)
print(a.size)
print(a)

#np.ones()
b = np.ones((1,2))
print(b.shape)
print(b.size)
print(b)

#np.full()
c= np.full((2,2), 7)
print(c.shape)
print(c.size)
print(c)

#np.eye()
d=np.eye(2)
print(d.shape)
print(d.size)
print(d)

#np.random.random()
e = np.random.random((2,2))
print(e)


(2, 2)
4
[[0. 0.]
 [0. 0.]]
(1, 2)
2
[[1. 1.]]
(2, 2)
4
[[7 7]
 [7 7]]
(2, 2)
4
[[1. 0.]
 [0. 1.]]
[[0.9326166  0.06062956]
 [0.48181978 0.07529023]]


In [60]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a", a)
print(a[0,1])

b=a[:2,1:3]
print("b",b)
print(a[0,1])
b[0,0] = 77
print(b[0,0])
print(a[0,1])

a [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
b [[2 3]
 [6 7]]
2
77
77


In [41]:
#평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
#표준정규분포

array5=np.random.normal(0,1,(3,3))
print(array5)

[[ 0.93999159 -0.95275682 -0.37167499]
 [-0.36693241  2.10968798  0.776697  ]
 [-0.51766954  1.29721886  1.61392175]]


In [42]:
#배열 합치기 : 가로축으로 합치기
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])
array8 = np.concatenate([array6,array7])
print(array8)
print(array8.shape)


[1 2 3 4 5 6]
(6,)


In [43]:
#배열 형태 바꾸기 
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2)

[[1 2]
 [3 4]]


In [44]:
#배열합치기 : 세로축으로 합치기 
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)


[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


In [45]:

array3 = np.concatenate([array1,array2],axis = 0)
print(array3)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [46]:
#형태 나누기

array = np.arange(8).reshape(2,4)
left,right = np.split(array, [2], axis = 1)  #array 를 index 2 를 기준으로 axis = 1(열)로 나눈다 
print(array)
print(left.shape)
print(right.shape)
print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
